### PR TITLE
Allow use of node 16 in CI

### PR DESCRIPTION
**Pull request by mborland**
GHA has changed the default node version breaking builds. Allow the use of node16 since node20 (the new default) does not work.

### CODE REVIEW

**Comment by mborland** [comment]
Boost.Test failures should be fixed by: https://github.com/boostorg/test/pull/421

**Comment by correaa** [comment]
Ok, thanks! 

do I wait for the fix in Boost.Test to be merged?

**Comment by mborland** [comment]
> Ok, thanks!
> 
> do I wait for the fix in Boost.Test to be merged?

I just merged the fix into Boost.Test develop branch so it should be good now.

**Comment by correaa** [comment]
mmm, still getting an error. not sure if I rerun the workflow too early https://github.com/correaa/boost-multi/actions/runs/9841457410/job/27182984846

**Comment by mborland** [comment]
> mmm, still getting an error. not sure if I rerun the workflow too early https://github.com/correaa/boost-multi/actions/runs/9841457410/job/27182984846

It's possible. I also have the patch cycling to merge into master: https://github.com/boostorg/test/pull/422, in case that is what you are pulling from.

**Comment by correaa** [comment]
the codecov/posix workflow is still picking the Boost.Test problem.

https://github.com/correaa/boost-multi/actions/runs/9841457410/job/27182984846?pr=48#step:12:134

**Comment by correaa** [comment]
> > the codecov/posix workflow is still picking the Boost.Test problem.
> > https://github.com/correaa/boost-multi/actions/runs/9841457410/job/27182984846?pr=48#step:12:134
> 
> I'm not sure what that one is building off of. It looks like it should be master since it says version 1.86 (the next one), and master picked up the changes: [boostorg/boost@3de5c2f](https://github.com/boostorg/boost/commit/3de5c2f6faa3f6d60ee34de24ed4a47acaa5aa66). Do you have Codecov running fine on your Gitlab CI? If so we could disable the GitHub one for now.

We could do that, yes. Codecov is working on gitlab. 

Is this codecov being even reported somewhere?

**Comment by mborland** [comment]
> Is this codecov being even reported somewhere?

From the most recent passing run looks like the answer is no: https://github.com/correaa/boost-multi/actions/runs/9719653836/job/26829810460#step:14:113.

**Comment by mborland** [comment]
Everything is back to green now

**Pull request merged**
