### PR TITLE
Add boost CI

### PR DESCRIPTION
**Pull request by mborland**
Includes CI and Codecov uploader that will make comments on PRs.
Closes: https://github.com/correaa/boost-multi/issues/11

### CODE REVIEW

**Comment by correaa** [comment]
Once of the errors I seems to come from inside Boost.Test

https://github.com/correaa/boost-multi/actions/runs/8847309449/job/24294903683?pr=31#step:7:1327

```
In file included from libs/test/src/framework.cpp:16:
./boost/test/impl/framework.ipp: In function ‘bool boost::unit_test::framework::impl::parse_filters(boost::unit_test::test_unit_id, boost::unit_test::test_unit_id_list&, boost::unit_test::test_unit_id_list&)’:
./boost/test/impl/framework.ipp:403:37: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  403 |     std::vector<std::string> const& filters = runtime_config::get<std::vector<std::string> >( runtime_config::btrt_run_filters );
```

seems to be a false positive to me.

**Comment by correaa** [comment]
```
// Some versions of Clang throw warnings that stl uses class std::tuple_size instead
// of struct std::tuple_size like it should be
#ifdef __clang__
#  pragma clang diagnostic push
#  pragma clang diagnostic ignored "-Wmismatched-tags"
#endif
```

should I use `class`, I am ok with it.

**Comment by correaa** [comment]
there is an unmatched `clang pop` now.

**Comment by correaa** [comment]
I think this branch needs to be rebased to fix the failing `CI / posix` jobs.

**Comment by correaa** [comment]
I made MSVC work using the option `/permissive-` in MSVC 19.14. 
Does this option still exists? 
Is that option used by Boost CI?

**Comment by mborland** [comment]
> I made MSVC work using the option `/permissive-` in MSVC 19.14 sometime ago.
> 
> Does this option still exists? Is that option used by Boost CI?

That option still exists yes. I would not rely on it because it allows non-conformant code blocks to be allowed. You could be passing on nefarious behavior to the user.

**Comment by mborland** [comment]
> ```
> // Some versions of Clang throw warnings that stl uses class std::tuple_size instead
> // of struct std::tuple_size like it should be
> #ifdef __clang__
> #  pragma clang diagnostic push
> #  pragma clang diagnostic ignored "-Wmismatched-tags"
> #endif
> ```
> 
> should I use `class`?, I am ok with it.

What you have is correct, we can ignore clang's complaints safely. You'll see the same thing with MSVC if you ever overload `std::numeric_limits`.

**Comment by correaa** [comment]
> > I made MSVC work using the option `/permissive-` in MSVC 19.14 sometime ago.
> > Does this option still exists? Is that option used by Boost CI?
> 
> That option still exists yes. I would not rely on it because it allows non-conformant code blocks to be allowed. You could be passing on nefarious behavior to the user.

Confusingly, this option is to force conformant code (note the `-` in `/permissive-`).

**Pull request merged**
